Repository ncsugroup17/my-cookbook, pull requests merged in 2025-02, with the labels that each got.

#1 Mworkuk/favorites page
  api/requirements.txt
  frontend/package.json
  frontend/src/features/AppContent/AppContent.tsx
  frontend/src/features/AppContent/HomePage/Favorite.tsx
  frontend/src/features/AppContent/HomePage/Profile.tsx
  frontend/src/features/AppContent/HomePage/Signup.tsx
  frontend/src/features/AppContent/RecipeInformation/RecipeFavoriteButton.tsx
  frontend/src/features/AppContent/RecipeInformation/RecipeInformation.tsx
  frontend/src/features/Header/Header.tsx
  frontend/src/features/Navbar/Navbar.tsx
Labels: enhancement

#14 Getting the coverage
  .github/workflows/python-test.yml
  api/Dockerfile
  api/main.py
  api/routes.py
  frontend/package.json
  frontend/src/features/AppContent/HomePage/Favorite.test.tsx
  frontend/src/features/AppContent/HomePage/Favorite.tsx
  frontend/src/features/AppContent/HomePage/HomePage.test.tsx
  frontend/src/features/AppContent/HomePage/MealPage.test.tsx
  frontend/src/features/AppContent/RecipeInformation/RecipeInformation.test.tsx
  frontend/src/features/AppContent/RecipeInformation/RecipeInformation.tsx
  frontend/src/features/Header/Header.test.tsx
  frontend/src/features/Navbar/Navbar.test.tsx
  frontend/src/features/ShoppingList/SmartShoppingList.test.tsx
  frontend/src/setupTests.ts
  tests/.coverage
  tests/.env
  tests/__pycache__/test_api.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_api.cpython-310-pytest-8.3.4.pyc
  tests/__pycache__/test_api_add_recipe.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_api_ingredients.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_api_meal_plan.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_api_nutrition_chatbot.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_api_root.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_api_search.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_api_search_name.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_eg.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_eg.cpython-310-pytest-8.3.4.pyc
  tests/__pycache__/test_login.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_login.cpython-310-pytest-8.3.4.pyc
  tests/__pycache__/test_shopping_list.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_shopping_list.cpython-310-pytest-8.3.4.pyc
  tests/test_api.py
  tests/test_api_add_recipe.py
  tests/test_api_ingredients.py
  tests/test_api_meal_plan.py
  tests/test_api_nutrition_chatbot.py
  tests/test_api_root.py
  tests/test_api_search.py
  tests/test_api_search_name.py
  tests/test_eg.py
  tests/test_login.py
  tests/test_shopping_list.py
Labels: enhancement

#16 Mworkuk/update readme
  README.md
Labels: documentation

#19 Fixes #18 The bug in recipe route is fixed
  api/routes.py
  tests/__pycache__/test_api_add_recipe.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_api_meal_plan.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_api_root.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_api_search.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_api_search2.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_api_search_name.cpython-310-pytest-7.4.2.pyc
  tests/test_api_root.py
  tests/test_api_search_name.py
Labels: bug

#22 Update readme
  .coverage
  .github/workflows/pdoc.yml
  README.md
  images/image-1.png
  images/image-10.png
  images/image-11.png
  images/image-12.png
  images/image-13.png
  images/image-14.png
  images/image-15.png
  images/image-16.png
  images/image-17.png
  images/image-2.png
  images/image-3.png
  images/image-4.png
  images/image-5.png
  images/image-6.png
  images/image-7.png
  images/image-8.png
  images/image-9.png
  images/image.png
  tests/.coverage
  tests/__pycache__/test_api_meal_plan.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_api_root.cpython-310-pytest-7.4.2.pyc
  tests/__pycache__/test_api_search_name.cpython-310-pytest-7.4.2.pyc
Labels: bug

#23 Trying to fix pdocs
  .github/workflows/pdoc.yml
Labels: bug

#24 Adding new feature
  .github/workflows/python-test.yml
  README.md
Labels: bug
